version: "3.8"

services:
  app:
    image: docker-web-app:latest
    container_name: student-mgmt-app
    env variables:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"
